### ISSUE TITLE
Resize the mod icon.

### ISSUE THREAD

**Issue by K0-RR** [ZestyBlaze/DimensionalOres#2]
Why?
- because it is the cause of about 80% of the mod weight
- the dimensions are huge and the icon in the Mod Menu is tiny, users can't see its full resolution (256x256 is definitely enough, please then use some lossless compression tool like Leanify or Oxipng)

**Comment by RDKRACZ** [comment]
Or I will do it for you and PR later today, will also add issues and homepage tag to the fabric.mod.json file and update the Gradle.
