### ISSUE TITLE
Idea?

### ISSUE THREAD

**Issue by TheeMrCheeky** [ZestyBlaze/DimensionalOres#6]
At least from what I have mined nether coal maybe make it (haven't tested diamond) Give a small amount of experience when mined? Like normal world blocks do when you mine emeralds, lapis lazuli, coal and diamond.

**Comment by ZestyBlaze** [comment]
I'll take a look into doing it ASAP, I'll try figure out how to do that

**Comment by ZestyBlaze** [comment]
This is now a feature in 1.18-1.0.6
