### ISSUE TITLE
[1.18.2+] Should ores be based on OreBlock instead of Block class?

### ISSUE THREAD

**Issue by kwpugh** [ZestyBlaze/DimensionalOres#7]
Hi,

A player brought up an issue that my ore vein enchantment does not work on dim ores.  I noticed that you extend Block rather than OreBlock.  Not sure if that was intended or not.  using OreBlock would help with mod compatibility.  My enchantment code filters on instanceof OreBlock to only break nearby ores.

Regards,

Kevin

**Comment by kwpugh** [comment]
open issue: https://github.com/kwpugh/MoreGems/issues/50

**Comment by ZestyBlaze** [comment]
Hi Kevin thanks for bringing this to my attention, I never realised there was an OreBlock class, I'll fix this as soon as I can

Cheers
Blaze

**Comment by ZestyBlaze** [comment]
Fixed
